# Change to your own
API_KEY: "XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
API_SECRET_KEY: "XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
ACCESS_TOKEN: "XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
ACCESS_TOKEN_SECRET: "XXXXXXXXXXXXXXXXXXXXXXXXXXXX"
